name: 'VUnit Action'
description: 'Automatically test your VHDL code with VUnit'

inputs:
  cmd:
    description: 'VUnit run script or command (Python)'
    default: './run.py'
  image:
    description: 'Container image to run the script/command on'
    default: ghdl/vunit:mcode

runs:
  using: "composite"
  steps:
    - run: docker run --rm -v $(pwd):/src -w /src ${{ inputs.image }} ${{ inputs.cmd }}
      shell: bash

branding:
  icon: cpu
  color: blue
