# action.yml
name: 'VUnit Action'
description: 'Automatically test your vhdl code with VUnit'
inputs:
  run_file:
    description: 'python VUnit run file'
    default: 'run.py'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.run_file }}
branding:
  icon: cpu
  color: blue
